### ISSUE TITLE
Duplicate YAML keys

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/talos_metapkg_ros_control_sot#13]
Hi @olivier-stasse,

Lines 14 to 25 are exactly lines 26 to 37 here:

https://github.com/stack-of-tasks/talos-metapkg-ros-control-sot/blob/41c559c6c88f7d1d791b7145924634b7b00e71b6/roscontrol_sot_talos/config/sot_talos_params_gazebo_effort.yaml#L26

Did you forget to replace legs by arms (and add the 7th joint), or should we control only legs here and remove lines 26 to 37 ?

**Comment by olivier-stasse** [comment]
Yes you are right it should be arm and not leg...
