### ISSUE TITLE
How to achieve torque control with the stack-of-tasks?

### ISSUE THREAD

**Issue by pi-q** [stack-of-tasks/talos_metapkg_ros_control_sot#4]
Hi! We would be interested in testing the stack-of-tasks for torque control with our Talos robot, but might need a little bit of guidance on how to make things work.

So far, we have installed stack-of-tasks software from robotpkg (sot-core, talos-dev, simple-humanoid-description, parametric-curves, tsid, soth), with the addition of [sot-torque-control](https://github.com/stack-of-tasks/sot-torque-control) and [talos-torque-control](https://github.com/pyrene-dev/talos-torque-control).

For some reason, I can't successfully get the robot to follow trajectories with torque control in Gazebo. Is there maybe something we are missing that we should know of?

I hope you can help! I am aware there is a lot of details missing in my question, just let me know what information you might need and I will provide it from there. Just to let you know, there is another very similar issue that I opened [here](https://github.com/pyrene-dev/talos-torque-control/issues/6), but I was not sure I would get a reply from that side.

Thanks!

**Comment by jcarpent** [comment]
I think you may also consider using TSID(https://github.com/stack-of-tasks/tsid), which may be seen as a simplified version.
There are some slides on the webside of @andreadelprete: https://andreadelprete.github.io/#teaching concerning TSID with basic tutorials.

**Comment by pi-q** [comment]
Thanks for your reply, @jcarpent! That was indeed the initial idea. In [sot-torque-control](https://github.com/stack-of-tasks/sot-torque-control), when I found the [inverse-dynamics-balance-controller](https://github.com/stack-of-tasks/sot-torque-control/blob/master/src/inverse-dynamics-balance-controller.cpp), I was hoping it would be straightforward to use it for computing desired joint torques, and then obtaining joint currents with the [joint-torque-controller](https://github.com/stack-of-tasks/sot-torque-control/blob/master/src/joint-torque-controller.cpp), but I have not had much luck with this approach. Which is why I asked if there might be something we are missing that we should know of?

**Comment by olivier-stasse** [comment]
Thanks @jcarpent for the answer.
sot-torque-control is a general wrapper for TSID. It is initially based on some previous work related to HRP-2 (see https://hal.archives-ouvertes.fr/hal-01574819 for details). talos-torque-control is indeed the current development package we are using to perform torque-control specific to TALOS on top of sot-torque-control.

You can use talos-torque-control with Gazebo for whole-body control without walking. @ramuzat did a jupyter notebook with tsid and TALOS to try out ideas. You can contact her to get the files, we did not yet integrate this in the infrastructure but hope to do it soon.

Right now we are focusing on walking using admittance control with actuators in position control mode at the low level.

There will be a workshop at Humanoids 2019 where I will present more details in the infra structure. We can probable interact more at this time, but in the meantime do not hesitate to ask more details. However please consider that, as probably like you, a lot people in the team are currently busy with the ICRA deadline.

**Comment by olivier-stasse** [comment]
@pi-q talos-torque-control is still somewhat immature. I would be quite cautious in its usage on a real TALOS humanoid robot.

**Comment by pi-q** [comment]
Thank you for the details, @olivier-stasse! No worries, we will be careful, and hopefully see you at Humanoids!

**Comment by olivier-stasse** [comment]
Torque control is achieved through TSID encapsulated in sot-torque-control and talos torque control see https://github.com/stack-of-tasks/talos-torque-control/issues/6.
We are almost there thanks to @NoelieRamuzat and @nim65s
