### ISSUE TITLE
Starting roscontrol_sot_talos with start_talos_gazebo_16_04.py not working

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/talos_metapkg_ros_control_sot#8]
Starting the SoT with TALOS in gazebo is not working in 16.04 in latest binary release.

**Comment by nim65s** [comment]
It's not working in 18.04 either. ref https://github.com/stack-of-tasks/talos_integration_tests/issues/3

**Comment by nim65s** [comment]
oops, that is actually another issue, my bad.
